import logging

from aap import Aap, AriaInventory, AriaHosts
from aap.aria_group_mapping import AriaGroupMapping
from aap.aria_groups import AriaGroups

log = logging.getLogger(__name__)


def abx_update(context: object, inputs: dict) -> dict:
    """
        This handler UPDATES an inventory on an ansible automation platform server
        and reruns the job template.

        Args:
            context: The context object containing information about the ABX event.
            inputs: The inputs provided for the ABX event.
        Returns:
            dict: The outputs generated by the ABX handler.
    """
    log.info(f"Updating resources for project: {inputs.get('__metadata').get('project')}")

    # Connect to server
    with Aap.from_aria(context=context, inputs=inputs) as aap:

        # Find organization
        # Must exist or default will be used if unset
        organization_name = inputs.get('organization_name')
        log.info(f"Organization name: '{organization_name}'")
        aap_organization = aap.search_organizations(name=organization_name)
        if len(aap_organization) == 0:
            msg = f"Could not find an organization with name '{organization_name}' on server '{aap.base_url}'"
            log.critical(msg)
            raise ValueError(msg)
        if len(aap_organization) > 1:
            msg = f"Found multiple an organization with name '{organization_name}' on server '{aap.base_url}'"
            log.critical(msg)
            raise ValueError(msg)
        #aap_organization = aap_organization[0]

        # Find Job Template
        # Must exist, no defaults
        job_template_name = inputs.get('job_template_name')
        log.info(f"Job Template name: '{job_template_name}'")
        aap_job_template = aap.search_job_templates(name=job_template_name)
        if len(aap_job_template) == 0:
            msg = f"Could not find a job template with name '{job_template_name}' on server '{aap.base_url}'"
            log.critical(msg)
            raise ValueError(msg)
        if len(aap_job_template) > 1:
            msg = f"Found multiple a job template with name '{job_template_name}' on server '{aap.base_url}'"
            log.critical(msg)
            raise ValueError(msg)
        aap_job_template = aap_job_template[0]

        # Find inventory
        # Must NOT exist
        inventory_name = inputs.get('inventory_name')
        log.info(f"Inventory name: '{inventory_name}'")
        aap_inventory = aap.search_inventories(name=inventory_name)
        if len(aap_inventory) == 0:
            msg = f"Could not find an inventory with name '{job_template_name}' on server '{aap.base_url}'"
            log.critical(msg)
            raise ValueError(msg)
        if len(aap_inventory) > 1:
            msg = f"Found multiple job inventory with name '{organization_name}' on server '{aap.base_url}'"
            log.critical(msg)
            raise ValueError(msg)
        aap_inventory = aap_inventory[0]

        # Update inventory
        log.info(f"Updating inventory '{inventory_name}")
        aap_inventory = aap.update_inventory(inventory=aap_inventory,
                                             updated=AriaInventory.from_aria(inputs=inputs))

        # Update hosts in inventory
        log.info(f"Update hosts in inventory")
        aap_hosts = aap.update_inventory_hosts(hosts=AriaHosts.from_aria(inputs=inputs),
                                               inventory=aap_inventory)

        # Update groups in inventory
        log.info("Update groups in inventory")
        aap_groups = aap.update_inventory_groups(groups=AriaGroups.from_aria(inputs=inputs),
                                                 inventory=aap_inventory)

        # Update hosts in groups
        log.info("Update hosts in groups")
        aap.update_hosts_to_groups(mapping=AriaGroupMapping.from_aria(inputs=inputs),
                                   groups=aap_groups,
                                   inventory=aap_inventory)

        # Launch job template
        log.info(f"Launching job template with inventory")
        aap_job = aap.launch_job_template(job_template=aap_job_template, inventory=aap_inventory)

        # Wait for job completion
        log.info(f"Wait for job completion")
        aap_job = aap.wait_on_job(job=aap_job)

        # Print job result
        match aap_job.status.lower():
            case 'successful':
                log.info(aap_job)
            case 'error' | 'failed' | 'cancel' | 'canceled':
                log.error(aap_job)
            case _:
                log.warning(aap_job)

        outputs = inputs
        outputs['update'] = True
        # outputs['id'] = aap_inventory.id
        # outputs['status'] = aap_job.status

        return outputs

